apiVersion: v1
kind: ConfigMap
metadata:
  name: huyouan-config
  namespace: huyouan
data:
  NODE_ENV: production
  PORT: "4000"
  JWT_EXPIRES_IN: "8h"
  RESEND_FROM_EMAIL: "no-reply@huyouan.local"
  CORS_ORIGIN: "http://huyouan.local,http://admin.huyouan.local"
  NEXT_PUBLIC_SITE_URL: "http://huyouan.local"
