apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huyouan
  namespace: huyouan
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: huyouan.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port: { number: 4000 }
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: server
                port: { number: 4000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: { number: 3000 }
    - host: admin.huyouan.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port: { number: 4000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port: { number: 3001 }
